version: '2'

services:

  docker-malware-scan:
    image: gjyoung1974/docker-malware-scan
    container_name: docker-malware-scan
    # uncomment and set the email address to receive email alerts when viruses are detected
    #command:
    # - /usr/local/install_alerts.sh email@example.net
    volumes:
      - ./data/queue:/data/av/queue
      - ./data/ok:/data/av/ok
      - ./data/nok:/data/av/nok
    #  - ./data/quarantine:/data/av/quarantine
    networks:
      - avnetwork

networks:
  avnetwork:
